### PR TITLE
Adding support for Mongo 3.0

### PR DESCRIPTION
**Pull request by yduponchel**
Removing dependencies to deprecated or method removed in mongo 3.0.

### CODE REVIEW

**Comment by magro** [comment]
Thanks! 

Because you removed `db.authenticate`, how is authentication supported now?

**Comment by yduponchel** [comment]
It seems that when we initialize the mongoclient with the uri, it reads the credentials at this point. This would make sense. To be honnest, i did not check the source, but i could authenticate to my server, so...

please also note that the plugin class (extends plugin) is also deprecated in Play 2.4, but i didn't have time to investigate this one.

Yann.
-- 
Sent from my HTC

----- Reply message -----

**Comment by magro** [comment]
Ok, so you probably used this format `mongodb://[username:password@]host1[:port1][,host2[:port2],...[,hostN[:portN]]][/[database][?options]]`?

**Comment by yduponchel** [comment]
Indeed. Anything bad with it? 

Actually the old approach was any reading the credentials from the uri itself, so if they were not in the uri, it would not have worked either.

Yann.
-- 
Sent from my HTC

----- Reply message -----

**Comment by magro** [comment]
Yeah, right, nothing wrong with it. Probably now authenticate is done implicitly if credentials are provided. I'll merge it and make a release the next days.

**Comment by magro** [comment]
I just released 0.9.0-jongo1.2 to maven central... Have fun!

**Comment by yduponchel** [comment]
Great, thanks.

Yann.
-- 
Sent from my HTC

----- Reply message -----

**Pull request merged**
