### PR TITLE
Update module to work with Play! 2.6.x

### LINKED ISSUE #66: Play 2.6 update
Hi. Play 2.6 was released a few days ago. Please could you update play-jongo to work with Play 2.6? Regards, Juan Carlos

### PR DESCRIPTION
**Pull request by greenled**
Fixes #66

### CODE REVIEW

**Comment by greenled** [comment]
Ok. Ready to merge.

**Comment by magro** [comment]
Thanks!

**Comment by greenled** [comment]
You're welcome. Thank you and the play-jongo team for the module.

**Comment by magro** [comment]
Sorry for the delay! I just released play-jongo 2.1.0-jongo1.3, it's now on its way to maven central...

**Comment by greenled** [comment]
Great! Thanks a lot

**Pull request merged**
